services:
    mysql:
        image: mysql:8-oracle
        command: --mysql-native-password=ON --lower-case-table-names=2
        healthcheck:
            test: mysql ogn --user=root --password='${MYSQL_PASSWORD}' --silent --execute "SELECT 1;"
            interval: 10s
            timeout: 10s
            retries: 10
        environment:
            MYSQL_ROOT_PASSWORD: '$MYSQL_PASSWORD'
        volumes:
            - ./conf/sql/docker:/docker-entrypoint-initdb.d
    next:
        build:
            context: .
            dockerfile: ./conf/Dockerfile
            target: next
            args:
                NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN: ${NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN?Mapbox token must be set}
                NEXT_PUBLIC_SITEURL: ${NEXT_PUBLIC_SITEURL}
                NEXT_PUBLIC_WEBSOCKET_HOST: $NEXT_PUBLIC_WEBSOCKET_HOST
                NEXT_PUBLIC_HISTORY_HOST: $NEXT_PUBLIC_HISTORY_HOST
                NEXT_PUBLIC_COMPETITION_DELAY: ${NEXT_PUBLIC_COMPETITION_DELAY:-0}
                MYSQL_PASSWORD: $MYSQL_PASSWORD
                MYSQL_HOST: mysql
                MYSQL_USER: root
                MYSQL_DATABASE: ogn
        command: yarn next start
        platform: 'linux/amd64'
        depends_on:
            mysql:
                condition: service_healthy
#        ports:
#            - 3000:3000
        environment:
            MYSQL_PASSWORD: $MYSQL_PASSWORD
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_DATABASE: ogn
            NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN: ${NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN?Mapbox token must be set}
            NEXT_PUBLIC_COMPETITION_DELAY: ${NEXT_PUBLIC_COMPETITION_DELAY:-0}
            NEXT_PUBLIC_WEBSOCKET_HOST: $NEXT_PUBLIC_WEBSOCKET_HOST
            NEXT_PUBLIC_HISTORY_HOST: ${NEXT_PUBLIC_HISTORY_HOST:-${NEXT_PUBLIC_WEBSOCKET_HOST}}
        restart: always
    ogn:
        build:
            target: ogn
            dockerfile: ./conf/Dockerfile
        command: node dist/bin/ogn
        platform: 'linux/amd64'
        depends_on:
            mysql:
                condition: service_healthy
        restart: always
        environment:
            MYSQL_PASSWORD: $MYSQL_PASSWORD
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_DATABASE: ogn
            NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN: $NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN
            NEXT_PUBLIC_SITEURL: $NEXT_PUBLIC_SITEURL
            NEXT_PUBLIC_COMPETITION_DELAY: ${NEXT_PUBLIC_COMPETITION_DELAY:-0}
            API_HOSTNAME: next:3000
#        ports:
#            - 8080:8080
        volumes:
            - ./db:/onglide/db
            - ./keys:/onglide/keys
    soaringspot:
        image: ghcr.io/ifly7charlie/ogn-soaringspot
        build:
            dockerfile: ./conf/Dockerfile
        command: node dist/bin/ssscrape.js
        platform: 'linux/amd64'
        depends_on:
            mysql:
                condition: service_healthy
        restart: always
        environment:
            MYSQL_PASSWORD: $MYSQL_PASSWORD
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_DATABASE: ogn
            NEXT_PUBLIC_SITEURL: $NEXT_PUBLIC_SITEURL
            SOARINGSPOT_URL: ${SOARINGSPOT_URL?SoaringSpot URL not set}
            SOARINGSPOT_OVERWRITE: ${SOARINGSPOT_OVERWRITE:-1}
            SOARINGSPOT_ACTUALS: ${SOARINGSPOT_ACTUALS:-1}
    apache:
        platform: 'linux/amd64'
        build:
            context: ./conf/apache
        restart: always
        command: httpd-foreground -D${ONGLIDE_SSL-NO_ONGLIDE_SSL}
        tty: true
        stdin_open: true
        depends_on:
            - next
            - ogn
        ports:
            - 8080:80
            - 8443:8443
        environment:
            NEXT_PUBLIC_SITEURL: ${NEXT_PUBLIC_SITEURL?URL for the site is not set}
            SERVER_ADMIN: $SERVER_ADMIN
