FROM node:18-slim
RUN apt-get update 
RUN apt-get install -y gnupg wget lsb-release
RUN wget -c https://dev.mysql.com/get/mysql-apt-config_0.8.23-1_all.deb
ENV DEBIAN_FRONTEND=noninteractive
RUN dpkg -i mysql-apt-config_0.8.23-1_all.deb
RUN apt-get update
RUN apt-get install -y mysql-community-client
RUN apt-get clean all
WORKDIR /onglide
COPY ./package.json ./
COPY ./yarn.lock ./
RUN yarn install --production --frozen-lockfile
