FROM node:16-alpine
ARG NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN
ENV NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN $NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN
WORKDIR /onglide
COPY package.json ./
RUN yarn install
COPY ./pages ./pages
COPY ./public ./public
COPY ./lib ./lib
COPY ./next.config.js ./next.config.js
COPY ./styles ./styles
COPY ./bin ./bin
RUN yarn next build
